:name: 'Basic'
:aliases:
  :reshell: "source ~/.bash_profile"
  :chamberlain: "ruby ~/coding/MeadHall/dotfiles/aliases/chamberlain/shell_boot.rb; reshell"
  ..: "cd .."
  ...: "cd ..."
  :lg: "ls -G"
  :la: "ls -AF"
  :ll: "ls -alh"
  :l: "ls -a"
  :l1: "ls -1"
  :lo: "ls -l | sed -e 's/--x/1/g' -e 's/-w-/2/g' -e 's/-wx/3/g' -e 's/r--/4/g' -e 's/r-x/5/g' -e 's/rw-/6/g' -e 's/rwx/7/g' -e 's/---/0/g'"
  :recent: "ls -lAt | head"
  :old: "ls -lAt | tail"
  :bashprof: "subl ~/.bash_profile"